apiVersion: v1
kind: Service
metadata:
  name: banking-backend
  namespace: banking
spec:
  selector:
    app: banking-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
